spring:
  application:
    name: menu-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/restaurantdb_menu
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
server:
  port: 9001
  tomcat:
    keep-alive-timeout: 15s
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

restaurant:
  greeting: Welcome to our restaurant portal !
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: refresh